package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Checkresult generated by hbm2java
 */
public class Checkresult implements java.io.Serializable {

	private int checkResultId;
	private Checkmethod checkmethod;
	private String result;
	private float punishScore;
	private Set<Supportdocument> supportdocuments = new HashSet<Supportdocument>(0);

	public Checkresult() {
	}

	public Checkresult(int checkResultId, Checkmethod checkmethod, String result, float punishScore) {
		this.checkResultId = checkResultId;
		this.checkmethod = checkmethod;
		this.result = result;
		this.punishScore = punishScore;
	}

	public Checkresult(int checkResultId, Checkmethod checkmethod, String result, float punishScore,
			Set<Supportdocument> supportdocuments) {
		this.checkResultId = checkResultId;
		this.checkmethod = checkmethod;
		this.result = result;
		this.punishScore = punishScore;
		this.supportdocuments = supportdocuments;
	}

	public int getCheckResultId() {
		return this.checkResultId;
	}

	public void setCheckResultId(int checkResultId) {
		this.checkResultId = checkResultId;
	}

	public Checkmethod getCheckmethod() {
		return this.checkmethod;
	}

	public void setCheckmethod(Checkmethod checkmethod) {
		this.checkmethod = checkmethod;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public float getPunishScore() {
		return this.punishScore;
	}

	public void setPunishScore(float punishScore) {
		this.punishScore = punishScore;
	}

	public Set<Supportdocument> getSupportdocuments() {
		return this.supportdocuments;
	}

	public void setSupportdocuments(Set<Supportdocument> supportdocuments) {
		this.supportdocuments = supportdocuments;
	}

}
