package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Checkmethod generated by hbm2java
 */
public class Checkmethod implements java.io.Serializable {

	private int checkMethodId;
	private Judgementsubitem judgementsubitem;
	private String checkMethodName;
	private Set<Checkresult> checkresults = new HashSet<Checkresult>(0);

	public Checkmethod() {
	}

	public Checkmethod(int checkMethodId, Judgementsubitem judgementsubitem, String checkMethodName) {
		this.checkMethodId = checkMethodId;
		this.judgementsubitem = judgementsubitem;
		this.checkMethodName = checkMethodName;
	}

	public Checkmethod(int checkMethodId, Judgementsubitem judgementsubitem, String checkMethodName,
			Set<Checkresult> checkresults) {
		this.checkMethodId = checkMethodId;
		this.judgementsubitem = judgementsubitem;
		this.checkMethodName = checkMethodName;
		this.checkresults = checkresults;
	}

	public int getCheckMethodId() {
		return this.checkMethodId;
	}

	public void setCheckMethodId(int checkMethodId) {
		this.checkMethodId = checkMethodId;
	}

	public Judgementsubitem getJudgementsubitem() {
		return this.judgementsubitem;
	}

	public void setJudgementsubitem(Judgementsubitem judgementsubitem) {
		this.judgementsubitem = judgementsubitem;
	}

	public String getCheckMethodName() {
		return this.checkMethodName;
	}

	public void setCheckMethodName(String checkMethodName) {
		this.checkMethodName = checkMethodName;
	}

	public Set<Checkresult> getCheckresults() {
		return this.checkresults;
	}

	public void setCheckresults(Set<Checkresult> checkresults) {
		this.checkresults = checkresults;
	}

}
