package com.nari.opfive.domain;
// Generated 2017-8-24 13:03:49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Checkresult generated by hbm2java
 */
@Entity
@Table(name = "checkresult", catalog = "leanassessment")
public class Checkresult implements java.io.Serializable {

	private int checkResultId;
	private Checkmethod checkmethod;
	private String result;
	private float punishScore;
	private Set supportdocuments = new HashSet(0);

	public Checkresult() {
	}

	public Checkresult(int checkResultId, Checkmethod checkmethod, String result, float punishScore) {
		this.checkResultId = checkResultId;
		this.checkmethod = checkmethod;
		this.result = result;
		this.punishScore = punishScore;
	}

	public Checkresult(int checkResultId, Checkmethod checkmethod, String result, float punishScore,
			Set supportdocuments) {
		this.checkResultId = checkResultId;
		this.checkmethod = checkmethod;
		this.result = result;
		this.punishScore = punishScore;
		this.supportdocuments = supportdocuments;
	}

	@Id

	@Column(name = "CheckResultID", unique = true, nullable = false)
	public int getCheckResultId() {
		return this.checkResultId;
	}

	public void setCheckResultId(int checkResultId) {
		this.checkResultId = checkResultId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CheckMethodID", nullable = false)
	public Checkmethod getCheckmethod() {
		return this.checkmethod;
	}

	public void setCheckmethod(Checkmethod checkmethod) {
		this.checkmethod = checkmethod;
	}

	@Column(name = "Result", nullable = false, length = 50)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "PunishScore", nullable = false, precision = 3)
	public float getPunishScore() {
		return this.punishScore;
	}

	public void setPunishScore(float punishScore) {
		this.punishScore = punishScore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checkresult")
	public Set getSupportdocuments() {
		return this.supportdocuments;
	}

	public void setSupportdocuments(Set supportdocuments) {
		this.supportdocuments = supportdocuments;
	}

}
