package com.nari.opfive.domain;
// Generated 2017-8-24 13:03:49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipment generated by hbm2java
 */
@Entity
@Table(name = "equipment", catalog = "leanassessment")
public class Equipment implements java.io.Serializable {

	private int eid;
	private String emanufacturer;
	private float assessTotalScore;
	private String ename;
	private String substationName;
	private String emodel;
	private Set tasks = new HashSet(0);

	public Equipment() {
	}

	public Equipment(int eid, String emanufacturer, float assessTotalScore, String ename, String substationName) {
		this.eid = eid;
		this.emanufacturer = emanufacturer;
		this.assessTotalScore = assessTotalScore;
		this.ename = ename;
		this.substationName = substationName;
	}

	public Equipment(int eid, String emanufacturer, float assessTotalScore, String ename, String substationName,
			String emodel, Set tasks) {
		this.eid = eid;
		this.emanufacturer = emanufacturer;
		this.assessTotalScore = assessTotalScore;
		this.ename = ename;
		this.substationName = substationName;
		this.emodel = emodel;
		this.tasks = tasks;
	}

	@Id

	@Column(name = "EID", unique = true, nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	@Column(name = "EManufacturer", nullable = false, length = 100)
	public String getEmanufacturer() {
		return this.emanufacturer;
	}

	public void setEmanufacturer(String emanufacturer) {
		this.emanufacturer = emanufacturer;
	}

	@Column(name = "AssessTotalScore", nullable = false, precision = 10)
	public float getAssessTotalScore() {
		return this.assessTotalScore;
	}

	public void setAssessTotalScore(float assessTotalScore) {
		this.assessTotalScore = assessTotalScore;
	}

	@Column(name = "EName", nullable = false, length = 100)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "SubstationName", nullable = false, length = 100)
	public String getSubstationName() {
		return this.substationName;
	}

	public void setSubstationName(String substationName) {
		this.substationName = substationName;
	}

	@Column(name = "EModel", length = 100)
	public String getEmodel() {
		return this.emodel;
	}

	public void setEmodel(String emodel) {
		this.emodel = emodel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipment")
	public Set getTasks() {
		return this.tasks;
	}

	public void setTasks(Set tasks) {
		this.tasks = tasks;
	}

}
