package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipment generated by hbm2java
 */
public class Equipment implements java.io.Serializable {

	private int eid;
	private String emanufacturer;
	private float assessTotalScore;
	private String ename;
	private String substationName;
	private String emodel;
	private Set<Task> tasks = new HashSet<Task>(0);

	public Equipment() {
	}

	public Equipment(int eid, String emanufacturer, float assessTotalScore, String ename, String substationName) {
		this.eid = eid;
		this.emanufacturer = emanufacturer;
		this.assessTotalScore = assessTotalScore;
		this.ename = ename;
		this.substationName = substationName;
	}

	public Equipment(int eid, String emanufacturer, float assessTotalScore, String ename, String substationName,
			String emodel, Set<Task> tasks) {
		this.eid = eid;
		this.emanufacturer = emanufacturer;
		this.assessTotalScore = assessTotalScore;
		this.ename = ename;
		this.substationName = substationName;
		this.emodel = emodel;
		this.tasks = tasks;
	}

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public String getEmanufacturer() {
		return this.emanufacturer;
	}

	public void setEmanufacturer(String emanufacturer) {
		this.emanufacturer = emanufacturer;
	}

	public float getAssessTotalScore() {
		return this.assessTotalScore;
	}

	public void setAssessTotalScore(float assessTotalScore) {
		this.assessTotalScore = assessTotalScore;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getSubstationName() {
		return this.substationName;
	}

	public void setSubstationName(String substationName) {
		this.substationName = substationName;
	}

	public String getEmodel() {
		return this.emodel;
	}

	public void setEmodel(String emodel) {
		this.emodel = emodel;
	}

	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
