package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Judgementsubitem generated by hbm2java
 */
public class Judgementsubitem implements java.io.Serializable {

	private int judgeSubItemId;
	private Judgementitem judgementitem;
	private String judgeSubitemName;
	private byte subitemStatement;
	private Set<Checkmethod> checkmethods = new HashSet<Checkmethod>(0);

	public Judgementsubitem() {
	}

	public Judgementsubitem(int judgeSubItemId, Judgementitem judgementitem, String judgeSubitemName,
			byte subitemStatement) {
		this.judgeSubItemId = judgeSubItemId;
		this.judgementitem = judgementitem;
		this.judgeSubitemName = judgeSubitemName;
		this.subitemStatement = subitemStatement;
	}

	public Judgementsubitem(int judgeSubItemId, Judgementitem judgementitem, String judgeSubitemName,
			byte subitemStatement, Set<Checkmethod> checkmethods) {
		this.judgeSubItemId = judgeSubItemId;
		this.judgementitem = judgementitem;
		this.judgeSubitemName = judgeSubitemName;
		this.subitemStatement = subitemStatement;
		this.checkmethods = checkmethods;
	}

	public int getJudgeSubItemId() {
		return this.judgeSubItemId;
	}

	public void setJudgeSubItemId(int judgeSubItemId) {
		this.judgeSubItemId = judgeSubItemId;
	}

	public Judgementitem getJudgementitem() {
		return this.judgementitem;
	}

	public void setJudgementitem(Judgementitem judgementitem) {
		this.judgementitem = judgementitem;
	}

	public String getJudgeSubitemName() {
		return this.judgeSubitemName;
	}

	public void setJudgeSubitemName(String judgeSubitemName) {
		this.judgeSubitemName = judgeSubitemName;
	}

	public byte getSubitemStatement() {
		return this.subitemStatement;
	}

	public void setSubitemStatement(byte subitemStatement) {
		this.subitemStatement = subitemStatement;
	}

	public Set<Checkmethod> getCheckmethods() {
		return this.checkmethods;
	}

	public void setCheckmethods(Set<Checkmethod> checkmethods) {
		this.checkmethods = checkmethods;
	}

}
