package com.nari.opfive.domain;
// Generated 2017-8-24 13:03:49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Judgementsubitem generated by hbm2java
 */
@Entity
@Table(name = "judgementsubitem", catalog = "leanassessment")
public class Judgementsubitem implements java.io.Serializable {

	private int judgeSubItemId;
	private Judgementitem judgementitem;
	private String judgeSubitemName;
	private byte subitemStatement;
	private Set checkmethods = new HashSet(0);

	public Judgementsubitem() {
	}

	public Judgementsubitem(int judgeSubItemId, Judgementitem judgementitem, String judgeSubitemName,
			byte subitemStatement) {
		this.judgeSubItemId = judgeSubItemId;
		this.judgementitem = judgementitem;
		this.judgeSubitemName = judgeSubitemName;
		this.subitemStatement = subitemStatement;
	}

	public Judgementsubitem(int judgeSubItemId, Judgementitem judgementitem, String judgeSubitemName,
			byte subitemStatement, Set checkmethods) {
		this.judgeSubItemId = judgeSubItemId;
		this.judgementitem = judgementitem;
		this.judgeSubitemName = judgeSubitemName;
		this.subitemStatement = subitemStatement;
		this.checkmethods = checkmethods;
	}

	@Id

	@Column(name = "JudgeSubItemID", unique = true, nullable = false)
	public int getJudgeSubItemId() {
		return this.judgeSubItemId;
	}

	public void setJudgeSubItemId(int judgeSubItemId) {
		this.judgeSubItemId = judgeSubItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JudgeItemID", nullable = false)
	public Judgementitem getJudgementitem() {
		return this.judgementitem;
	}

	public void setJudgementitem(Judgementitem judgementitem) {
		this.judgementitem = judgementitem;
	}

	@Column(name = "JudgeSubitemName", nullable = false, length = 150)
	public String getJudgeSubitemName() {
		return this.judgeSubitemName;
	}

	public void setJudgeSubitemName(String judgeSubitemName) {
		this.judgeSubitemName = judgeSubitemName;
	}

	@Column(name = "SubitemStatement", nullable = false)
	public byte getSubitemStatement() {
		return this.subitemStatement;
	}

	public void setSubitemStatement(byte subitemStatement) {
		this.subitemStatement = subitemStatement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "judgementsubitem")
	public Set getCheckmethods() {
		return this.checkmethods;
	}

	public void setCheckmethods(Set checkmethods) {
		this.checkmethods = checkmethods;
	}

}
