package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Judgementitem generated by hbm2java
 */
public class Judgementitem implements java.io.Serializable {

	private int judgeItemId;
	private Rootasseitem rootasseitem;
	private String judgeItemName;
	private byte judgeStatement;
	private Set<Judgementsubitem> judgementsubitems = new HashSet<Judgementsubitem>(0);

	public Judgementitem() {
	}

	public Judgementitem(int judgeItemId, Rootasseitem rootasseitem, String judgeItemName, byte judgeStatement) {
		this.judgeItemId = judgeItemId;
		this.rootasseitem = rootasseitem;
		this.judgeItemName = judgeItemName;
		this.judgeStatement = judgeStatement;
	}

	public Judgementitem(int judgeItemId, Rootasseitem rootasseitem, String judgeItemName, byte judgeStatement,
			Set<Judgementsubitem> judgementsubitems) {
		this.judgeItemId = judgeItemId;
		this.rootasseitem = rootasseitem;
		this.judgeItemName = judgeItemName;
		this.judgeStatement = judgeStatement;
		this.judgementsubitems = judgementsubitems;
	}

	public int getJudgeItemId() {
		return this.judgeItemId;
	}

	public void setJudgeItemId(int judgeItemId) {
		this.judgeItemId = judgeItemId;
	}

	public Rootasseitem getRootasseitem() {
		return this.rootasseitem;
	}

	public void setRootasseitem(Rootasseitem rootasseitem) {
		this.rootasseitem = rootasseitem;
	}

	public String getJudgeItemName() {
		return this.judgeItemName;
	}

	public void setJudgeItemName(String judgeItemName) {
		this.judgeItemName = judgeItemName;
	}

	public byte getJudgeStatement() {
		return this.judgeStatement;
	}

	public void setJudgeStatement(byte judgeStatement) {
		this.judgeStatement = judgeStatement;
	}

	public Set<Judgementsubitem> getJudgementsubitems() {
		return this.judgementsubitems;
	}

	public void setJudgementsubitems(Set<Judgementsubitem> judgementsubitems) {
		this.judgementsubitems = judgementsubitems;
	}

}
