package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rootasseitem generated by hbm2java
 */
public class Rootasseitem implements java.io.Serializable {

	private int rootAsseItemId;
	private Task task;
	private String rootAsseItemName;
	private Set<Judgementitem> judgementitems = new HashSet<Judgementitem>(0);

	public Rootasseitem() {
	}

	public Rootasseitem(int rootAsseItemId, Task task, String rootAsseItemName) {
		this.rootAsseItemId = rootAsseItemId;
		this.task = task;
		this.rootAsseItemName = rootAsseItemName;
	}

	public Rootasseitem(int rootAsseItemId, Task task, String rootAsseItemName, Set<Judgementitem> judgementitems) {
		this.rootAsseItemId = rootAsseItemId;
		this.task = task;
		this.rootAsseItemName = rootAsseItemName;
		this.judgementitems = judgementitems;
	}

	public int getRootAsseItemId() {
		return this.rootAsseItemId;
	}

	public void setRootAsseItemId(int rootAsseItemId) {
		this.rootAsseItemId = rootAsseItemId;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public String getRootAsseItemName() {
		return this.rootAsseItemName;
	}

	public void setRootAsseItemName(String rootAsseItemName) {
		this.rootAsseItemName = rootAsseItemName;
	}

	public Set<Judgementitem> getJudgementitems() {
		return this.judgementitems;
	}

	public void setJudgementitems(Set<Judgementitem> judgementitems) {
		this.judgementitems = judgementitems;
	}

}
