package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

/**
 * Supportdocument generated by hbm2java
 */
public class Supportdocument implements java.io.Serializable {

	private int suppDocId;
	private Checkresult checkresult;
	private String suppDocName;
	private String suppDocLocation;

	public Supportdocument() {
	}

	public Supportdocument(int suppDocId, Checkresult checkresult, String suppDocName, String suppDocLocation) {
		this.suppDocId = suppDocId;
		this.checkresult = checkresult;
		this.suppDocName = suppDocName;
		this.suppDocLocation = suppDocLocation;
	}

	public int getSuppDocId() {
		return this.suppDocId;
	}

	public void setSuppDocId(int suppDocId) {
		this.suppDocId = suppDocId;
	}

	public Checkresult getCheckresult() {
		return this.checkresult;
	}

	public void setCheckresult(Checkresult checkresult) {
		this.checkresult = checkresult;
	}

	public String getSuppDocName() {
		return this.suppDocName;
	}

	public void setSuppDocName(String suppDocName) {
		this.suppDocName = suppDocName;
	}

	public String getSuppDocLocation() {
		return this.suppDocLocation;
	}

	public void setSuppDocLocation(String suppDocLocation) {
		this.suppDocLocation = suppDocLocation;
	}

}
