package com.nari.opfive.domain;
// Generated 2017-8-24 13:03:49 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Supportdocument generated by hbm2java
 */
@Entity
@Table(name = "supportdocument", catalog = "leanassessment")
public class Supportdocument implements java.io.Serializable {

	private int suppDocId;
	private Checkresult checkresult;
	private String suppDocName;
	private String suppDocLocation;

	public Supportdocument() {
	}

	public Supportdocument(int suppDocId, Checkresult checkresult, String suppDocName, String suppDocLocation) {
		this.suppDocId = suppDocId;
		this.checkresult = checkresult;
		this.suppDocName = suppDocName;
		this.suppDocLocation = suppDocLocation;
	}

	@Id

	@Column(name = "SuppDocID", unique = true, nullable = false)
	public int getSuppDocId() {
		return this.suppDocId;
	}

	public void setSuppDocId(int suppDocId) {
		this.suppDocId = suppDocId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CheckResultID", nullable = false)
	public Checkresult getCheckresult() {
		return this.checkresult;
	}

	public void setCheckresult(Checkresult checkresult) {
		this.checkresult = checkresult;
	}

	@Column(name = "SuppDocName", nullable = false, length = 100)
	public String getSuppDocName() {
		return this.suppDocName;
	}

	public void setSuppDocName(String suppDocName) {
		this.suppDocName = suppDocName;
	}

	@Column(name = "SuppDocLocation", nullable = false, length = 100)
	public String getSuppDocLocation() {
		return this.suppDocLocation;
	}

	public void setSuppDocLocation(String suppDocLocation) {
		this.suppDocLocation = suppDocLocation;
	}

}
