package com.nari.opfive.domain;
// Generated 2017-8-25 11:17:32 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private int tid;
	private Equipment equipment;
	private Date taskTime;
	private Set<Taskoperator> taskoperators = new HashSet<Taskoperator>(0);
	private Set<Rootasseitem> rootasseitems = new HashSet<Rootasseitem>(0);

	public Task() {
	}

	public Task(int tid, Equipment equipment, Date taskTime) {
		this.tid = tid;
		this.equipment = equipment;
		this.taskTime = taskTime;
	}

	public Task(int tid, Equipment equipment, Date taskTime, Set<Taskoperator> taskoperators,
			Set<Rootasseitem> rootasseitems) {
		this.tid = tid;
		this.equipment = equipment;
		this.taskTime = taskTime;
		this.taskoperators = taskoperators;
		this.rootasseitems = rootasseitems;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	public Date getTaskTime() {
		return this.taskTime;
	}

	public void setTaskTime(Date taskTime) {
		this.taskTime = taskTime;
	}

	public Set<Taskoperator> getTaskoperators() {
		return this.taskoperators;
	}

	public void setTaskoperators(Set<Taskoperator> taskoperators) {
		this.taskoperators = taskoperators;
	}

	public Set<Rootasseitem> getRootasseitems() {
		return this.rootasseitems;
	}

	public void setRootasseitems(Set<Rootasseitem> rootasseitems) {
		this.rootasseitems = rootasseitems;
	}

}
